export const USERS_LIST = 'USERS_LIST';
export const USERS_LIST_REJECTED = 'USERS_LIST_REJECTED';
export const USERS_LIST_PENDING = 'USERS_LIST_PENDING';
export const USERS_LIST_FULFILLED = 'USERS_LIST_FULFILLED';
export const SET_DATA = 'SET_DATA';