export const USERS_LIST = 'USERS_LIST';
export const USERS_LIST_REJECTED = 'USERS_LIST_REJECTED';
export const USERS_LIST_PENDING = 'USERS_LIST_PENDING';
export const USERS_LIST_FULFILLED = 'USERS_LIST_FULFILLED';
export const SEARCH_USER = 'SEARCH_USER';
export const SEARCH_USER_FULFILLED = 'SEARCH_USER_FULFILLED';
export const REPO_DETAILS_FULFILLED = 'REPO_DETAILS_FULFILLED';